"""create customers and addresses

Revision ID: 0001
Revises:
Create Date: 2026-07-26 15:23:00.691046

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("identification", sa.String(length=64), nullable=False),
        sa.Column("age", sa.SmallInteger(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "btrim(identification) <> ''", name="ck_customers_identification_not_blank"
        ),
        sa.CheckConstraint("btrim(name) <> ''", name="ck_customers_name_not_blank"),
        sa.CheckConstraint("status IN ('ACTIVE', 'DELETED')", name="ck_customers_status"),
        sa.CheckConstraint("age >= 0 AND age <= 120", name="ck_customers_age_range"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email", name="ux_customers_email"),
        sa.UniqueConstraint("identification", name="ux_customers_identification"),
    )
    op.create_index("ix_customers_status", "customers", ["status"], unique=False)
    op.create_table(
        "addresses",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("btrim(address) <> ''", name="ck_addresses_address_not_blank"),
        sa.CheckConstraint("btrim(city) <> ''", name="ck_addresses_city_not_blank"),
        sa.CheckConstraint("btrim(country) <> ''", name="ck_addresses_country_not_blank"),
        sa.CheckConstraint("btrim(postal_code) <> ''", name="ck_addresses_postal_code_not_blank"),
        sa.CheckConstraint("btrim(state) <> ''", name="ck_addresses_state_not_blank"),
        sa.CheckConstraint("status IN ('ACTIVE', 'DELETED')", name="ck_addresses_status"),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_addresses_customer_id", "addresses", ["customer_id"], unique=False)
    op.create_index(
        "ix_addresses_customer_id_status", "addresses", ["customer_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_addresses_customer_id_status", table_name="addresses")
    op.drop_index("ix_addresses_customer_id", table_name="addresses")
    op.drop_table("addresses")
    op.drop_index("ix_customers_status", table_name="customers")
    op.drop_table("customers")
    # ### end Alembic commands ###
